### PR TITLE
Error marker types and label.

### LINKED ISSUE #264: Error marker types preferences do not use Eclipse wording
**Describe the bug**
The error marker types on the CogniCrypt Eclipse plug-in's preference page are named differently than on other Eclipse preference pages.

**To Reproduce**
1. Open the CogniCrypt preference page.
2. Open a drop-down list in the “Error-Marker Types” section. It shows “Problem”, “Warning”, “Secure”.

**Expected behavior**
Commonly used types like “Error”, “Warning”, “Info” should be used. Compare the preference pages “Java”/“Compiler”/“Errors/Warnings”, “Maven”/“Errors/Warnings”, or “SpotBugs”. Maybe the section “Error-Marker Types” should be renamed to “Errors/Warnings”.

**Desktop (please complete the following information):**
 - Version 1.0.0.201902280326

### PR DESCRIPTION
**Pull request by shahrzadav**
# Description

Changed the name of Error-marker types label in CogniCrypt preference page, and added "ignored" to error/warning types.

Fixes #264

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested on client project

**Test Configuration**:
* Eclipse Version: Oxygen.3a Release (4.7.3a)
* Java Version: 1.8
* OS: Windows 10

### CODE REVIEW

**Comment by shahrzadav** [comment]
@kruegers

File: plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/StaticAnalyzerPreferences.java [hunk 1]
```diff
@@ -140,7 +140,7 @@ private void createAdvancedContents(Composite parent) {
 		final Composite callGraphContainer = new Composite(staticAnalysisGroup, SWT.None);
 		callGraphContainer.setLayout(new GridLayout(2, true));
 		final Label label1 = new Label(callGraphContainer, SWT.SHADOW_IN);
-		label1.setText("Call-graph construction algorithm");
+		label1.setText("Call-graph constructiomarkern algorithm");
```
Comment (kruegers) [inline plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/StaticAnalyzerPreferences.java]: Is that a typo?

**Review by kruegers — CHANGES_REQUESTED** [review]
Thanks for the pull request. As far as I see, you haven't finished the implementation for 'ignored'.  If [this call](https://github.com/eclipse-cognicrypt/CogniCrypt/blob/master/plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/results/ResultsCCUIListener.java#L166) returns 'ignored', the respective marker should not be generated at all (i.e. 
```
if (sev == Severities.Ignored) {
  return; 
}
```
)

Please add this and take care of my comment below.

File: plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/StaticAnalyzerPreferences.java (hunk 1 above)
Comment (shahrzadav) [reply plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/StaticAnalyzerPreferences.java]: yes it is, I will fix it, thanks for noticing.

**Review by kruegers — APPROVED** [review]
